# Generated by Django 5.2.14 on 2026-06-03 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('Workshop', 'Workshop'), ('Seminar', 'Seminar'), ('Social', 'Social'), ('Competition', 'Competition'), ('Talk', 'Talk'), ('Hackathon', 'Hackathon')], default='Workshop', max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Draft', max_length=20)),
                ('show_on_landing', models.BooleanField(default=True)),
                ('seats_total', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Symposium', 'Symposium'), ('Open day', 'Open day'), ('Site visit', 'Site visit'), ('Panel', 'Panel'), ('Recurring', 'Recurring'), ('Milestone', 'Milestone'), ('Hackathon', 'Hackathon'), ('Other', 'Other')], default='Other', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('event_date', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', '-event_date'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('student_id', models.CharField(blank=True, max_length=50)),
                ('course', models.CharField(max_length=200)),
                ('year_of_study', models.PositiveSmallIntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4'), (5, 'Year 5')], default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Official',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role_title', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='officials/')),
                ('permission_level', models.CharField(choices=[('Admin', 'Admin'), ('Coordinator', 'Coordinator'), ('View-Only', 'View-Only')], default='Coordinator', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('quote', models.TextField(blank=True)),
                ('course', models.CharField(blank=True, max_length=200)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='EventAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_role', models.CharField(choices=[('Lead Organizer', 'Lead Organizer'), ('Logistics', 'Logistics'), ('Registration', 'Registration'), ('MC', 'MC'), ('Technical Support', 'Technical Support')], default='Lead Organizer', max_length=30)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.event')),
                ('official', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.official')),
            ],
            options={
                'unique_together': {('event', 'official')},
            },
        ),
    ]
