# Generated by Django 5.2.15 on 2026-07-06 06:44

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_announcement_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.event_cover_path),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.gallery_image_path),
        ),
        migrations.AlterField(
            model_name='official',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.official_photo_path),
        ),
    ]
